name: PR Test and Lint

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build
        run: make binary

      - name: Test
        run: make test

      - name: Lint
        run: make lint
